import express, { Request, Response } from 'express';
import cors from 'cors';
import { connectDB } from './db.js';
import customerRoutes from './routes/customer.js';
import employeeRoutes from './routes/employee.js';
import addressRoutes from './routes/address.js';
import productRoutes from './routes/product.js';
import categoryRoutes from './routes/category.js';
import productImageRoutes from './routes/productImage.js';
import targetRoutes from './routes/target.js';
import targetProductRoutes from './routes/targetProduct.js';
import colorRoutes from './routes/color.js';
import colorProductRoutes from './routes/colorProduct.js';
import flowerRoutes from './routes/flower.js';
import flowerProductRoutes from './routes/flowerProduct.js';
import materialRoutes from './routes/material.js';
import colorMaterialRoutes from './routes/colorMaterial.js';
import recipeRoutes from './routes/recipe.js';
import supplierRoutes from './routes/supplier.js';
import importSlipRoutes from './routes/importSlip.js';
import importSlipDetailRoutes from './routes/importSlipDetail.js';
import exportSlipRoutes from './routes/exportSlip.js';
import exportSlipDetailRoutes from './routes/exportSlipDetail.js';
import image3dRoutes from './routes/image3d.js';
import cartRoutes from './routes/cart.js';
import cartDetailRoutes from './routes/cartDetail.js';
import shippingPolicyRoutes from './routes/shippingPolicy.js';
import paymentPolicyRoutes from './routes/paymentPolicy.js';
import orderRoutes from './routes/order.js';
import orderDetailRoutes from './routes/orderDetail.js';
import paymentRoutes from './routes/payment.js';
import campaignRoutes from './routes/campaign.js';
import voucherRoutes from './routes/voucher.js';
import orderVoucherRoutes from './routes/orderVoucher.js';
import reviewRoutes from './routes/review.js';
import wishlistRoutes from './routes/wishlist.js';
import faqRoutes from './routes/faq.js';
import chatRoutes from './routes/chat.js';
import imageRequestRoutes from './routes/imageRequest.js';
import blogRoutes from './routes/blog.js';
import collectionRoutes from './routes/collection.js';
import collectionProductRoutes from './routes/collectionProduct.js';

const app = express();

app.use(cors());
app.use(express.json());

app.use('/api/customers', customerRoutes);
app.use('/api/employees', employeeRoutes);
app.use('/api/addresses', addressRoutes);
app.use('/api/products', productRoutes);
app.use('/api/categories', categoryRoutes);
app.use('/api/product-images', productImageRoutes);
app.use('/api/targets', targetRoutes);
app.use('/api/target-products', targetProductRoutes);
app.use('/api/colors', colorRoutes);
app.use('/api/color-products', colorProductRoutes);
app.use('/api/flowers', flowerRoutes);
app.use('/api/flower-products', flowerProductRoutes);
app.use('/api/materials', materialRoutes);
app.use('/api/color-materials', colorMaterialRoutes);
app.use('/api/recipes', recipeRoutes);
app.use('/api/suppliers', supplierRoutes);
app.use('/api/import-slips', importSlipRoutes);
app.use('/api/import-slip-details', importSlipDetailRoutes);
app.use('/api/export-slips', exportSlipRoutes);
app.use('/api/export-slip-details', exportSlipDetailRoutes);
app.use('/api/images-3d', image3dRoutes);
app.use('/api/carts', cartRoutes);
app.use('/api/cart-details', cartDetailRoutes);
app.use('/api/shipping-policies', shippingPolicyRoutes);
app.use('/api/payment-policies', paymentPolicyRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/order-details', orderDetailRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/campaigns', campaignRoutes);
app.use('/api/vouchers', voucherRoutes);
app.use('/api/order-vouchers', orderVoucherRoutes);
app.use('/api/reviews', reviewRoutes);
app.use('/api/wishlists', wishlistRoutes);
app.use('/api/faqs', faqRoutes);
app.use('/api/chats', chatRoutes);
app.use('/api/image-requests', imageRequestRoutes);
app.use('/api/blogs', blogRoutes);
app.use('/api/collections', collectionRoutes);
app.use('/api/collection-products', collectionProductRoutes);

app.get('/', (req: Request, res: Response) => {
    res.send('Backend TIEM_HOA_YEN đang chạy!');
});

const PORT = 3000;

(async () => {
    await connectDB();
    app.listen(PORT, () => {
        console.log(`\nServer: http://localhost:${PORT}`);
        console.log('\nCác endpoint:');
    console.log(`  /api/customers`);
    console.log(`  /api/employees`);
    console.log(`  /api/addresses`);
    console.log(`  /api/products`);
    console.log(`  /api/categories`);
    console.log(`  /api/product-images`);
    console.log(`  /api/targets`);
    console.log(`  /api/target-products`);
    console.log(`  /api/colors`);
    console.log(`  /api/color-products`);
    console.log(`  /api/flowers`);
    console.log(`  /api/flower-products`);
    console.log(`  /api/materials`);
    console.log(`  /api/color-materials`);
    console.log(`  /api/recipes`);
    console.log(`  /api/suppliers`);
    console.log(`  /api/import-slips`);
    console.log(`  /api/import-slip-details`);
    console.log(`  /api/export-slips`);
    console.log(`  /api/export-slip-details`);
    console.log(`  /api/images-3d`);
    console.log(`  /api/carts`);
    console.log(`  /api/cart-details`);
    console.log(`  /api/shipping-policies`);
    console.log(`  /api/payment-policies`);
    console.log(`  /api/orders`);
    console.log(`  /api/order-details`);
    console.log(`  /api/payments`);
    console.log(`  /api/campaigns`);
    console.log(`  /api/vouchers`);
    console.log(`  /api/order-vouchers`);
    console.log(`  /api/reviews`);
    console.log(`  /api/wishlists`);
    console.log(`  /api/faqs`);
    console.log(`  /api/chats`);
    console.log(`  /api/image-requests`);
    console.log(`  /api/blogs`);
    console.log(`  /api/collections`);
    console.log(`  /api/collection-products`);
    });
})();
